### PR TITLE
- corrects bug in http syntax

### PR DESCRIPTION
**Pull request by iamemilio**
@danmcp @rudolphpienaar 
- removes obnoxious printing, and uses qprint
- --version now works
- fixed bug with http syntax that created incorrect url's

### CODE REVIEW

**Comment by iamemilio** [comment]
@rudolphpienaar revert the changes to pfcon for now, and let me do some more testing on this. Dont merge

**Comment by rudolphpienaar** [comment]
Ok -- did you revert already or should I?

**Comment by iamemilio** [comment]
I dont know how. Is that something I can do?

**Comment by iamemilio** [comment]
We may need @danmcp to help us

**Comment by danmcp** [comment]
@iamemilio Either you can do it or we can do it for you.  You can revert with git revert <commit_id>.  Then make a new pull request with those changes.

**Comment by iamemilio** [comment]
Ok I can do that. I can put it out in an hour or two

**Comment by iamemilio** [comment]
im going to close this pull request, and make a pull request to revert back to the stable version. Sorry for the trouble!

**Comment by iamemilio** [comment]
@danmcp Im having a bit of a hard time understanding how to determine which mainline number I should pick. I might need some help

**Pull request closed without merging**
